version: "3"
volumes:
  code_share:
services: 
    server:
        container_name: custom_alpine
        build: 
            context: ./app-server
            dockerfile: Dockerfile
        ports: 
            - "8080:80"
        volumes: 
            - ./:/www/
        tty: true